### ISSUE TITLE
MINOR: R.home("bin")

### ISSUE THREAD

**Issue by HenrikBengtsson** [richfitz/redux#11]
A minor suggestion. Use `file.path(R.home("bin"), "Rscript")` instead of `file.path(R.home(), "bin", "Rscript")` such that it picks up the same arch (and not the default) on mulit-arch installs, e.g. Windows.

**Comment by richfitz** [comment]
Thanks! I did not know that and have had issues with finding Rscript on windows before - this is quite probably the culprit
