### ISSUE TITLE
Unable to interrupt $BRPOP

### ISSUE THREAD

**Issue by alanault** [richfitz/redux#16]
Hi

Thanks for the great package!

I'm using it to have a R script listen out for a message, before processing some input files. I'm using $BRPOP for this. However, when I test with a zero timeout (so it's waiting forever), or indeed with any timeout, it's impossible to interrupt the process - I have to kill R to get control back.

Am I missing something obvious? I had a similar setup with the rredis package and a simple CTRL+C usually sufficed...

Thanks
Alan

```
library(redux)
r <- hiredis()
# hangs, but returns control after 30s
r$BRPOP(key = "test", 30)
# hangs, but never returns control, necessitating kill
r$BRPOP(key = "test", 0)
```

**Comment by richfitz** [comment]
No, sorry - this is a limitation of the underlying C library.  Once we get into library C code there is no way of polling for interrupts.  So you should wrap your `BRPOP` calls within a loop of R code.  Something like

```r
brpop_forever_safe <- function(con, key) {
  repeat {
    res <- con$BRPOP(key, 1)
    if (!is.null(res)) {
      return(res)
    }
  }
}
```

(untested!) which will be interruptable but poll forever
