### ISSUE TITLE
Closing connection

### ISSUE THREAD

**Issue by riccardopinosio** [richfitz/redux#18]
Hello,

Thanks a lot for your work on this, it's excellent! I'm using your package at work now and I love it.
I was wondering however, what command to use to close the connection to redis opened using hiredis(). I looked through the docs but couldn't find anything, is it necessary to close the connection?

Best,
Riccardo.

**Comment by richfitz** [comment]
No, it's not necessary - it will be closed automatically when the object goes out of scope and is garbage collected
