### ISSUE TITLE
support for parallel processing

### ISSUE THREAD

**Issue by picarus** [richfitz/redux#19]
I have an R program that works fine using Redux.
Now I am trying to parallelize the process and I am finding that I get:

Error in { : 
  task 10 failed - "Failure communicating with the Redis server"

I am using foreach and %dopar% and apparently they are not getting along well but the message is not very clear on what actions to take

My redis is based on AWS ElasticCache, if that makes a difference.

**Comment by richfitz** [comment]
This is most likely because the redis connection object does not survive serialisation.  That's an issue with most db connectors I think.  I'm preparing a CRAN re-release and will take a look

**Comment by richfitz** [comment]
Any chance you could send a minimal example?

**Comment by richfitz** [comment]
Hmm, it's not the pointer serialisation:

```r
cl <- parallel::makePSOCKcluster(2)
con <- redux::hiredis()
parallel::clusterApply(cl = cl, c("a", "b"), con$GET)
parallel::stopCluster(cl)
```

that gives

```
Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: Context is not connected
```

whereas the error you are seeing is coming from the reply-to-sexp code which can only happen _after_ the connection has been found to be ok.  If you can send an example I will look

**Comment by picarus** [comment]
Sorry, I can't share code. 
I would say if you wrap your code in a foreach %dopar% structure you should be able to see the problem.
Still, the error message you see and then one I get seem quite related. Happy to take advise on how to use the API in parallel way following any other pattern.

This is how I build my cluster:

library(foreach)
library(redux)   # for the cache
library(jsonlite)
library(futile.logger) # this is used to create logs
library(doParallel)

if (PARALLEL) {
  nrcores <- detectCores()/2
  flog.warn("GOING PARALLEL with %d cores", nrcores)
  registerDoParallel(cores=nrcores)
}

output <- foreach (i = seq_len(nrow(dt)), .combine=rbindignore, .inorder=F) %dopar% {

# write here your redux code,
# a get to check if the value already exists
# a set to store if it does not exist after calculating

}

**Comment by richfitz** [comment]
I can't reproduce this at all.

```r
library(foreach)
library(redux)   # for the cache
library(jsonlite)
library(doParallel)

registerDoParallel(cores=2)

output <- foreach(
  i = seq_len(4),
  .inorder=FALSE) %dopar% {

    con <- hiredis()
    key <- sprintf("key_%d", i)
    if (!con$EXISTS(key)) {
      con$SET(key, i)
    }
}
```

I understand that people can't share code that is confidential to their work, but a minimal reproducible example is needed for me to be able to do anything with this.  Sorry, but I can't do anything further.  Please reopen if end up with code you can share (or anyone else finding this via google and the same problem).

**Comment by picarus** [comment]
Do not create the connection inside the foreach loop. That I created outside the loop.
I am no longer working on that project, so can't do the reproducible example as do not have access to the infrastructure or data.
As mentioned in a former message, your first attempt shows a similar error, related to the con.
